Backend/lab4/lab4/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lab4.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','app.views.index',name='index'),
    url(r'^category/$', 'app.views.category'),
    url(r'^item/$', 'app.views.item'),
    url(r'^category/(?P<slug>[\w-]+)/$', 'app.views.detailsCategory'),
    url(r'^item/(?P<item_id>\d+)/$', 'app.views.detailsItem'),
    url(r'^about/$', 'app.views.about'),
    url(r'^items/add/$','app.views.add_item', name="add_item"),
)

Backend/lab4/app/models.py
from django.db import models

L_TYPES = (
	('t', 'Para resolver'),
	('l', 'Para revisar'),
	('p', 'No resuelto'),
	)

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255,unique=True)

	def __unicode__(self):
		return "%s - %s" % (self.name, self.slug)

class Item(models.Model):
	listing = models.CharField(max_length = 1,choices=L_TYPES, default = 't')
	name = models.CharField(max_length = 120)
	category = models.ForeignKey(Category)
	department = models.CharField(max_length = 255)
	description = models.TextField()
	posted_on =  models.DateTimeField(auto_now_add = True)
	updated_on =  models.DateTimeField()

	def __unicode__(self):
		return "%s - %s" % (self.name, self.category)

class Pictures(models.Model):
	item = models.ForeignKey(Item)
	url = models.CharField(max_length=255)

Backend/lab4/app/forms.py
from django import forms 
from app.models import L_TYPES, Category

class ItemForm(forms.Form):
	listing = forms.ChoiceField(choices=L_TYPES, initial='t')
	name = forms.CharField(max_length=255)
	category = forms.ModelChoiceField(Category.objects.all())
	department = forms.CharField(max_length=255)
	description = forms.CharField(widget=forms.Textarea)
	updated_on = forms.DateTimeField()

Backend/lab4/app/views.py
from django.shortcuts import render_to_response, get_object_or_404, HttpResponseRedirect
from django.template import Context, RequestContext
from app.models import Item
from app.models import Category
from app.forms import ItemForm


def index(request):
	context = Context({'title':'Hola CIDEI'})
	return render_to_response('index.html',context)

def category(request):
	categories = Category.objects.all()
	context = Context({'title':'Categorias','categories':categories})
	return render_to_response('category.html',context)

def item(request):
	items = Item.objects.all()
	context = Context({'title':'Items','items':items})
	return render_to_response('item.html',context)

def detailsCategory(request, slug):
	category = get_object_or_404(Category, slug=slug)
	context = Context({
		'title':'Detalle de %s:' % category.name, 
		'category' :category
	})
	return render_to_response('detailsCategory.html', context)


def detailsItem(request, item_id):
	item = get_object_or_404(Item, id=item_id)
	context = Context({
		'title':'Detalle de %s:' % item.name, 
		'item' :item
	})
	return render_to_response('detailsItem.html', context)

def about(request):
	context = Context({'title':'Acerca de mi empresa', 'text':'Departamento: Magni harum excepturi voluptatum vero pariatur? Fugiat illo rem velit ipsa ducimus perspiciatis, est voluptatem quasi placeat error eos sunt eius tempore minima aperiam, labore placeat consectetur '})
	return render_to_response('about.html',context)

def add_item(request):
	if request.method == "POST":
		form = ItemForm(request.POST)
		if form.is_valid():
			#Crear un nuevo item
			item = Item.objects.create(
				listing = form.cleaned_data['listing'],
				name = form.cleaned_data['name'],
				category = form.cleaned_data['category'],
				department = form.cleaned_data['department'],
				description = form.cleaned_data['description'],
				updated_on = form.cleaned_data['updated_on'],
				)

			return HttpResponseRedirect('/item/%s/' % item.id)

	else:
		form = ItemForm()

	context = Context({'title':'Adicionar item', 'form':form})
	return render_to_response("form.html",context, context_instance = RequestContext(request))

Backend/lab4/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h2>{{ title }}</h2>
		<p>{{ text }}</p>
	</body>		
</html>

Backend/lab4/templates/category.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			{% for category in categories %}
				<li><a href="{{ category.slug }}/">{{ category.name|capfirst}}</a></li>
			{% endfor %}
		</ul>
	</body>		
</html>

Backend/lab4/templates/details.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			<li>Nombre: {{item.name}}</li>
			<li>Categoria: {{item.category.name}}</li>
			<li>Listado: {{item.get_listing_display}}</li>
			<li>Departamento: {{item.department}}</li>
			<li>Creado: {{item.posted_on|date}}</li>
		</ul>
		<h2>Descripcion</h2>
		<p>{{item.description|linebreaksbr}}</p>
	</body>
</html>

Backend/lab4/templates/detailsCategory.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			<li>Nombre: {{category.name}}</li>
			<li>Slug: {{category.slug}}</li>
		</ul>
	</body>
</html>

Backend/lab4/templates/detailsItem.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			<li>Nombre: {{item.name}}</li>
			<li>Categoria: {{item.category.name}}</li>
			<li>Listado: {{item.get_listing_display}}</li>
			<li>Departamento: {{item.department}}</li>
			<li>Creado: {{item.posted_on|date}}</li>
		</ul>
		<h2>Descripcion</h2>
		<p>{{item.description|linebreaksbr}}</p>
	</body>
</html>

Backend/lab4/templates/form.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<form action="." method="POST">
			{%csrf_token%}
			{{ form.as_p }}
			<input type="submit" value="Enviar">
		</form>
	</body>		
</html>

Backend/lab4/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			<li><a href="category/">Categorias</a></li>
			<li><a href="item/">Items</a></li>
			<li><a href="about/">About</a></li>
			<li><a href="items/add/">Adicionar item</a></li>
		</ul>
	</body>
</html>

Backend/lab4/templates/item.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			{% for item in items %}
				<li><a href="{{ item.id }}/">{{ item.name|capfirst}}</a></li>
			{% endfor %}
		</ul>
	</body>		
</html>